project:
  type: website
  output-dir: docs

website:
  title: "Tim Chen"
  site-url: "https://weitingchen.com"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: pages/courses.qmd
        text: Courses
      - text: Hobbies
        menu:
          - href: pages/coffee.qmd
            text: Coffee
      - text: Projects
        menu:
          - projects/student-analysis.qmd
          - projects/ml-challenge.qmd
          - projects/toronto-crime-analysis.qmd
          - projects/us-presidential-election.qmd
          - projects/toronto-shelter-analysis.qmd
          - projects/bike-theft-analysis.qmd
          - projects/imdb-analysis.qmd
          - projects/mayohr-intern.qmd
          - projects/traffic-collision-analysis.qmd
      - href: https://timsplayland.vercel.app/
        text: Portfolio
      - text: "Resume"
        href: assets/pdfs/resume_2025.pdf
      - icon: github
        href: https://github.com/timchen0326
      - icon: envelope
        href: "mailto:timchen0326ca@gmail.com"

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true

execute:
  freeze: true
