---
title: "Tim Chen"
about:
  template: trestles
  links:
    - text: "Resume"
      href: pdfs/resume.pdf
    - icon: envelope
      text: "Email"
      href: "mailto:timchen0326ca@gmail.com"
    - icon: github
      text: "GitHub"
      href: https://github.com/timchen0326
    - icon: linkedin
      text: "LinkedIn"
      href: https://www.linkedin.com/in/timchen0326/
---

I am an Honours Bachelor of Science (HBSc) student at the University of Toronto, specializing in Mathematics and its Applications (Probability & Statistics) with minors in Computer Science and Statistics. I am passionate about using data-driven methods to solve real-world problems, particularly through statistical analysis, machine learning, and data visualization.

In my academic journey, I have completed relevant coursework in **Machine Learning (Python)**, **Statistical Theory**, **Databases (SQL)**, and **Software Design (Java)**, among others.

I have professional experience as a **Frontend Software Engineer Intern** at MAYOHR, where I enhanced customer service efficiency and streamlined backend integration using Python and JavaScript.

I am skilled in a variety of programming languages, including **Python, R, SQL, Java, and C**, as well as tools like **Tableau, Power BI, and Excel**. My certifications include the **Google Data Analytics Professional Certificate**, showcasing expertise in data cleaning, visualization, and statistical analysis.

### Professional Experience

#### **Frontend Software Engineer Intern, MAYOHR**  
- Built and maintained a high-traffic website using JavaScript, HTML, and CSS, enabling a 30% faster resolution time for customer service inquiries.  
- Reduced integration bottlenecks by 25% through Python-based frontend testing before backend implementation.  
- Collaborated with product managers to design features that increased troubleshooting efficiency by 40%.
---

### Education

**University of Toronto**  
**Honours Bachelor of Science (HBSc)** in Mathematics & Its Applications (Probability & Statistics)  
- Relevant Coursework: **Machine Learning (Python)**, **Statistical Theory**, **Databases (SQL)**, **Software Design (Java)**  
- Expected Graduation: **2026**

---

### Skills

- **Programming Languages:** Python, R, SQL, Java, C  
- **Data Tools:** Tableau, Power BI, Excel  
- **Certifications:** Google Data Analytics Professional Certificate  
 
