{
  "hash": "d7b816da6766d3d175944e96d4f979f9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Student Habits & Academic Performance Analysis\"\nauthor: \"Tim Chen\"\ndate: \"2025-05-18\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    number-sections: true\nexecute:\n  echo: false\n  warning: false\n  error: false\n---\n\n# Introduction\n\nThis report provides an in-depth analysis of the **Student Habits and Academic Performance** dataset, exploring how demographic, lifestyle, and psychological factors relate to exam outcomes. We cover data loading, cleaning, exploratory visualization, feature engineering, predictive modeling, and interpret key findings in light of recent global developments.\n\n# Setup and Data Loading\n\nWe begin by importing core Python libraries and loading the CSV file into a pandas DataFrame.\n\n\n\n# Data Source\n\nThis analysis uses the \"Student Habits and Academic Performance\" dataset sourced from Kaggle (Aryan208). The dataset and accompanying code are available at: ([kaggle.com](https://www.kaggle.com/datasets/aryan208/student-habits-and-academic-performance-dataset/data))\n\n# Data Overview\n\nA quick summary reveals:\n\n* **80,000** student records, each with **31** features (demographics, habits, support, and performance).\n* No missing values detected across any columns.\n* Key summary statistics:\n\n  * **Study Hours/Day**: mean \\~4.17 hrs, median \\~4.13 hrs, range 0–12 hrs.\n  * **Attendance %**: centered around \\~70% with a span of 40–100%.\n  * **Sleep Hours**: most students sleep between 6–8 hrs.\n  * **Exam Score**: skewed high, median 93, with many perfect scores (100).\n\nThese sleep patterns resonate with findings from an NIH‑funded study (Mathew & Hale 2024) showing that **irregular bedtimes and inconsistent sleep** are significantly associated with poorer grades and behavior problems among adolescents ([wgrt.com](https://wgrt.com/irregular-sleep-patterns-tied-to-poor-grades-and-behavioral-issues-among-teens-nih-funded-study-finds/?utm_source=chatgpt.com)).\n\n::: {#255cd024 .cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n       study_hours_per_day  attendance_percentage   sleep_hours    exam_score\ncount         80000.000000           80000.000000  80000.000000  80000.000000\nmean              4.174388              69.967884      7.017417     89.141350\nstd               2.004135              17.333015      1.467377     11.591497\nmin               0.000000              40.000000      4.000000     36.000000\n25%               2.800000              55.000000      6.000000     82.000000\n50%               4.125624              69.900000      7.000000     93.000000\n75%               5.500000              84.900000      8.000000    100.000000\nmax              12.000000             100.000000     12.000000    100.000000\n```\n:::\n:::\n\n\n# Data Cleaning & Preprocessing\n\nAll categorical columns were cast to the `category` type and text entries standardized (e.g., `Yes`/`No` to lowercase). No rows were removed.\n\n\n\n# Exploratory Data Analysis (EDA)\n\n## Univariate Distributions\n\n* **Study Hours** show a roughly normal distribution with a right tail (some students study up to 12 hrs).\n* **Attendance** is left-skewed: most students attend at least 70% of classes.\n* **Sleep** peaks around 7 hrs.\n* **Exam Score** heavily clusters at high values, indicating a ceiling effect.\n\nThis ceiling effect mirrors global exam trends, where extraordinary clustering at top scores challenges differentiation. In India’s NEET‑UG 2024, **67 candidates scored a perfect 720/720**, sparking debate about score inflation and exam fairness (Times of India 2024) ([timesofindia.indiatimes.com](https://timesofindia.indiatimes.com/city/mumbai/67-students-achieve-perfect-720-in-neet-ug-questions-raised/articleshow/110749121.cms?utm_source=chatgpt.com)).\n\n::: {#f1786de6 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-5-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-5-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-5-output-3.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-5-output-4.png){}\n:::\n:::\n\n\n## Categorical Insights\n\n* **Majors**: Arts (16.9%), Business (16.3%), Computer Science (14.8%), etc.\n* **Gender**: roughly equal representation of Male and Female, with a small Other category.\n* **Learning Styles**: Kinesthetic most common (\\~20%), followed by Reading and Auditory.\n\n::: {#ac83ec44 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-6-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-6-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-6-output-3.png){}\n:::\n:::\n\n\n## Correlation Analysis\n\nA heatmap of key numeric features indicates:\n\n* **Study Hours & Exam Score**: moderate positive correlation (\\~0.35).\n* **Sleep Hours & Exam Score**: mild positive correlation (\\~0.20).\n* **Attendance & Exam Score**: weaker but positive (\\~0.15).\n\n::: {#b3e57bea .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-7-output-1.png){}\n:::\n:::\n\n\nAlthough study time correlates with performance, excessive workload shows **diminishing returns**. A systematic review of K–12 homework found that while homework generally benefits learning, **too much increases cognitive load and reduces motivation**, ultimately impairing achievement (Guo et al. 2024) ([pubmed.ncbi.nlm.nih.gov](https://pubmed.ncbi.nlm.nih.gov/39297020/?utm_source=chatgpt.com)).\n\n# Feature Engineering\n\nTwo new features were created:\n\n1. **Age Group** (<=18, 19–22, 23–26, 27+) to capture life‑stage differences.\n2. **Total Screen Time**: sum of social media, Netflix, and overall screen usage.\n\n\n\nGlobal policies increasingly address **digital distractions**. In England, secondary schools with **effective mobile phone bans** were found more than twice as likely to be rated outstanding and saw students achieve **one to two grades higher** on GCSE exams, underscoring the impact of screen management on learning (Busby 2024) ([independent.co.uk](https://www.independent.co.uk/news/education/school-mobile-phone-pupils-law-b2536892.html?utm_source=chatgpt.com)).\n\n# Predictive Modeling\n\nA baseline Linear Regression model was built using four features:\n\n* Study Hours/Day\n* Sleep Hours\n* Motivation Level\n* Time Management Score\n\n::: {#f1d546e1 .cell execution_count=8}\n\n::: {.cell-output .cell-output-stdout}\n```\nRMSE: 10.88\nR²:   0.125\n```\n:::\n:::\n\n\n# Results & Interpretation\n\n* **RMSE ≈ 10.88**: on average, predictions deviate by \\~11 points (out of 100).\n* **R² ≈ 0.125**: the model explains only \\~12.5% of variance, indicating substantial unexplained factors.\n* **Residual Plot** shows wide scatter, suggesting nonlinearity and missing predictor variables.\n\n::: {#0d01dd82 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](student-analysis_files/figure-html/cell-10-output-1.png){}\n:::\n:::\n\n\n# Conclusion & Next Steps\n\nOur analysis confirms that while study habits, sleep, and time management are positively associated with academic outcomes, their effects are **moderate** and subject to external influences. Recent global trends—from exam score clustering in high‑stakes tests to nuanced homework policies and phone bans—corroborate our findings and highlight the importance of balanced, evidence‑based interventions.\n\n**Recommendations:**\n\n1. Test non‑linear models (e.g., Random Forest, XGBoost) to capture complex relationships.\n2. Incorporate additional predictors such as **total\\_screen\\_time** and **previous\\_gpa**.\n3. Perform cross‑validation and hyperparameter tuning.\n4. Explore classification approaches for dropout risk and policy impact analysis.\n\n",
    "supporting": [
      "student-analysis_files"
    ],
    "filters": [],
    "includes": {}
  }
}